import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { setBillData } from '../store/billSlice';

export default function Bill() {

  const navigate = useNavigate();
  const dispatch = useDispatch();
  const senderName = localStorage.getItem("senderName") || "N/A";
  const quantity = localStorage.getItem("quantity") || "0";
  const price = localStorage.getItem("price") || "0.0";

  function gotoadmin(e) {
    e.preventDefault();
  }

  return (
    <div className="row billbackground">
      <div className="rowww">
        <h1 id="text">Your pickup request is created successfully</h1>
        <div className="billbox">
          <div className="bill">
            <p className="billdata">Your bill is generated by name: {senderName}</p>
            <p className="billdata">Quantity is: {quantity}</p>
            <p className="billdata">Total amount is: ₹{price}</p>
            <button id="paybutton" type="submit" onClick={gotoadmin}>Pay Bill</button>
          </div>
        </div>
      </div>
    </div>
  );
}
